### ISSUE TITLE
pop from an empty set

### ISSUE THREAD

**Issue by Das-Kampfnudelholz** [EchterAlsFake/PHUB#34]
I'm trying to make an little API in flask and after using it 2 times i get 

    File "c:\Users\happy\Downloads\index.py", line 47, in get_videos

    search_results = client.search(value)
                     ^^^^^^^^^^^^^^^^^^^^

    File "C:\Users\happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\phub\core.py", line 244, in search

    if (not (locals._allowed_sort_types in param)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    File "C:\Users\happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\phub\objects\param.py", line 151, in __contains__

    item_value = item_values.pop()
                 ^^^^^^^^^^^^^^^^^

    KeyError: 'pop from an empty set'

**Comment by Egsagon** [comment]
Hi

How did you do that

**Comment by Horikumi** [comment]
> I'm trying to make an little API in flask and after using it 2 times i get
> 
> ```
> File "c:\Users\happy\Downloads\index.py", line 47, in get_videos
> 
> search_results = client.search(value)
>                  ^^^^^^^^^^^^^^^^^^^^
> 
> File "C:\Users\happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\phub\core.py", line 244, in search
> 
> if (not (locals._allowed_sort_types in param)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "C:\Users\happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\phub\objects\param.py", line 151, in __contains__
> 
> item_value = item_values.pop()
>              ^^^^^^^^^^^^^^^^^
> 
> KeyError: 'pop from an empty set'
> ```

Same issue I'm using python 3.12 still same issue any fix ?

**Comment by Egsagon** [comment]
Hi
- What version of PHUB are you using
- What search parameters (if any) did you pass
