### ISSUE TITLE
how to get direct link url for download.

### ISSUE THREAD

**Issue by bobwatcherx** [EchterAlsFake/PHUB#44]
is there a way to just get the download url? and I don't want to download it on my computer. So I want to get the upload URL to paste on my video hosting

give me example code thx

**Comment by Egsagon** [comment]
Not really. You can get the m3u8 URL:
```python
url = video.get_M3U_url(quality = 'best')
```
And later call ffmpeg or another m3u8 downloader.
Keep in mind the url as an expiration time.

**Comment by bobwatcherx** [comment]
but I copy and paste the URL to a remote video hosting such as filemoon.sx and it doesn't work. and errors. I want the video URL to be able to be remotely uploaded. is there any solution for that? so that the mp4 is automatically downloaded
![Screenshot 2024-01-24 154448](https://github.com/EchterAlsFake/PHUB/assets/52072811/29ae74bb-2114-40dd-a7c4-f7796595e9b3)

**Comment by Egsagon** [comment]
```python
# Get remote sources
sources = video.fetch('page@mediaDefinitions')
remote_source_url = [s for s in sources if 'remote' in s][0]['videoUrl']

# Get by quality
remote_source = client.call(remote_source_url).json()
qualities = {int(s['quality']): s['videoUrl'] for s in remote_source}
url = phub.Quality( 'best' ).select(qualities)
```
I don't know if this requires specific headers.
This is experimental, maybe it'll be implemented in the video object.

**Comment by Egsagon** [comment]
Implemented with latest commit:
```python
url = video.get_direct_url(quality = 'best')
```

**Comment by Egsagon** [comment]
Coming back on this. Pornhub will refuse to serve you these videos if you do not have the exact same cookies as the PHUB client.
If your download service supports using custom cookies, you can pass the ones from `client.session.cookies`.
Otherwise, you will have to download it yourself and pass it to your server.
