### ISSUE TITLE
Issue with search function

### ISSUE THREAD

**Issue by Horikumi** [EchterAlsFake/PHUB#47]
I'm using python 3.12

I just did

import phub
api = phub.Client()
hel = api.search('abela danger')

This works 1 or 2 times mostly after that it starts giving KeyError: 'pop from an empty set'

Any fix ?

**Comment by Egsagon** [comment]
Hi, what version of PHUB are you using? Looking at the traceback you posted in #34, you may have an outdated version of PHUB. Maybe try update it with `pip install --upgrade phub`.
Hope this helps!

**Comment by Horikumi** [comment]
I did that still same issue
phub 4.4.2

**Comment by Egsagon** [comment]
I'm not able to replicate the issue. What's the traceboack?

**Comment by Horikumi** [comment]
'pop from an empty set'
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
await handler.callback(self.client, *args)
File "/workspace/bot.py", line 91, in search_command
videos = api.search(query)
^^^^^^^^^^^^^^^^^
File "/app/.heroku/python/lib/python3.12/site-packages/phub/core.py", line 273, in search
if (not (locals._allowed_sort_types in param)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.heroku/python/lib/python3.12/site-packages/phub/objects/param.py", line 150, in __contains__
item_value = item_values.pop()
^^^^^^^^^^^^^^^^^
KeyError: 'pop from an empty set'

**Comment by Egsagon** [comment]
Can paste this in your code after importing PHUB? This will print out used variables because i cannot replicate your bug.

```py
def patch(self, query: phub.Param):
    
    self._assert_self(query)
    assert len(query.value) == 1, f'{query} must be an un-modified Param constant to be compared.'
    
    print(f'{phub.locals._allowed_sort_types.value = }')
    print(f'{phub.locals._sort_period_types.value = }')
    print(f'{query = } ; {query.value = }')
    
    item_key, item_values = list(query.value.items())[0]
    
    print(f'{item_key = }')
    print(f'{item_values = }')
    
    item_value = item_values.pop()
    
    for key, values in self.value.items():
        if key == item_key and item_value in values:
            return True
    
    return False

phub.Param.__contains__ = patch
```

**Comment by Egsagon** [comment]
Nevermind, got the bug

**Comment by Egsagon** [comment]
Hey, this should be fixed now. Please udpate once again with `pip install --upgrade phub` and let me know if there are any more errors!

**Comment by Horikumi** [comment]
Same issue again

**Comment by Egsagon** [comment]
update again, wrong commit sorry

**Comment by Horikumi** [comment]
Fixed, thank you
