### ISSUE TITLE
search options not working properly

### ISSUE THREAD

**Issue by rlleshi** [EchterAlsFake/PHUB#53]
Hi there,

so here's a minimal example:

```
import phub

client = phub.Client()

query = client.search(query=None, category='amateur', sort='views', production='professional')

for video in query.sample(max=10):
    print(video.title, video.views)
```

Results:

_AnalTrixxx - Tattooed Alt Spinner Paisley Paige Anal Fucked Hard 54681
CEI Cum Eating Encouragement Instruction JOI POV Positive Femdom 146748
Colombian Beauty Mary Gomez Meets And Fucked Her New Boyfriend - MAMACITAZ 11263
SANTA CAME TO FUCK IN MY HOUSE 57502
Sissy Boy Crossdressing And Bisexual Domination Porn 883
Заехал в гости , малыха оказалась гостеприимной 83819
WOWGIRLS Very sensual lesbian scene starring amazing girls Evelin Elle and Molly Devon 148789
Erotic oiled massage squirt shaking orgasm 111685
Sweet Heart Video - April Olsen Tells Harley Haze To Dump Their Boyfriends & Play With Each Other 102658
NicoRD fucks my stepsister on my vacation ft Lynnscream ANAL 70149_

switching production to 'homemade' gives the same results:

_AnalTrixxx - Tattooed Alt Spinner Paisley Paige Anal Fucked Hard 54681
CEI Cum Eating Encouragement Instruction JOI POV Positive Femdom 146748
Colombian Beauty Mary Gomez Meets And Fucked Her New Boyfriend - MAMACITAZ 11263
SANTA CAME TO FUCK IN MY HOUSE 57502
Sissy Boy Crossdressing And Bisexual Domination Porn 883
Заехал в гости , малыха оказалась гостеприимной 83819
WOWGIRLS Very sensual lesbian scene starring amazing girls Evelin Elle and Molly Devon 148789
Erotic oiled massage squirt shaking orgasm 118011
Sweet Heart Video - April Olsen Tells Harley Haze To Dump Their Boyfriends & Play With Each Other 102658
NicoRD fucks my stepsister on my vacation ft Lynnscream ANAL 70149_

Also, notice that they're not really sorted by views

**Comment by Egsagon** [comment]
Hey!

The query parameter can't be None, it must be a string. Otherwise i guess it probably fucks up pornhub search page and you are getting random recommendations. If you want a blank search, use an empty string.

Thanks for reporting tho, i'll add a check for that just in case.

**Comment by rlleshi** [comment]
@Egsagon ty for the quick answer. Actually getting the same results even with the empty string. 

So, the same videos when changing the `production` & not really sorted according to views.

**Comment by Egsagon** [comment]
hmmm. I would have swear this worked yesterday. Have you tried with an non-empty query?

**Comment by rlleshi** [comment]
Seems to work with non-empty query. 

Doesn't work with whitespace " " though.

**Comment by Egsagon** [comment]
Just checked an yeah, queries can't be null anymore. Pornhub will just redirect to "recently featured" videos.

**Comment by rlleshi** [comment]
Ty for the quick reponses!
