### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by amiyoghoshstar** [EchterAlsFake/PHUB#57]
Hi
I am trying to login using this code snippet below.
`client = phub.Client("username","password")`

I am getting this error `phub.errors.LoginFailed: Invalid entry. Use a valid email address to log in.` I am using email as username. 

I have also inspected the official pornhub api request to login. Please check below
![image](https://github.com/EchterAlsFake/PHUB/assets/60391042/63cb810a-b260-4711-9820-4d188a881204)

As you can see the field name is email not username. So it might be a cause of this issue? 

Thank you!

**Comment by EchterAlsFake** [comment]
Hi,

Have you used the newest commits from this repository? Egsagon already fixed the release, but we haven't created a new Pypi release yet, because there are some other issues which need to be fixed.

Please install PHUB from git by executing: ˋpip install git+https://GitHub.com/EchterAlsFake/PHUBˋ

And let me know if it worked. Thanks :)

**Comment by amiyoghoshstar** [comment]
Thank you so much for you reply!

I am having another problem. when i try to install the package for python 3.10 using this suggested way `pip install --upgrade git+https://github.com/EchterAlsFake/PHUB.git@py-3.10`

It installs the package as UNKNOWN 0.0.0.0 

Do you know how to resolve this issue? @EchterAlsFake

**Comment by EchterAlsFake** [comment]
Hi, I have synced the py-3.10 branch with the new commits from master. Maybe you just try it again. 

(Never seen such an error lol)

**Comment by amiyoghoshstar** [comment]
![image](https://github.com/EchterAlsFake/PHUB/assets/60391042/f7dc4523-214f-4dbb-9dbd-eaddb6b1166c)
Still no success :(

**Comment by Egsagon** [comment]
Hi,
What about the compat branch? It should be compatible with py3.10.
The error you got is really weird, maybe also try to reset you env and/or uninstall and install back the package.
Hope that helps

**Comment by EchterAlsFake** [comment]
You pip version is out of date (like really out of date). Maybe do `pip install --upgrade pip`
