### ISSUE TITLE
Is there a way to list videos from channels by country

### ISSUE THREAD

**Issue by bobwatcherx** [EchterAlsFake/PHUB#58]
i see you docs but no find how to list video by channel and from country

example

`video = client.FindVideosByChannelCountry("india")`

then list all videos from channels from india country

and how to list channels and all videos from channels

`channels = client.VideosfromChannel("My channel")`

**Comment by Egsagon** [comment]
Hi again,

This API only provides basic methods to communicate with Pornhub. Here is what you can do to get users by country, and then list their videos (if I understand correctly):

```py
import client

client = phub.Client(...)

channels = client.search_user(
    country = ..., # The destination country
    has_videos = True, # Ensures the channel has videos on it
    # Add other channel filters here, eg. 'is_model' to make sure to get models only
)

# Then, iterate videos for each channel
for channel in channels:
    # In this example we only show their last 5 videos
    for video in channel.videos[:5]:
        print(video)
```

I'm not sure what you mean in your 2nd question, if you meant how to get videos from a channel, refer to my first response.

Hope this helps!
