### ISSUE TITLE
How to use This package without VPN or proxy

### ISSUE THREAD

**Issue by bobwatcherx** [EchterAlsFake/PHUB#59]
because pornhub and this package is blocked in my country . 
how to use this package with proxy or if possible even without a proxy .
because i will make backend with this package for my web
thx

**Comment by Egsagon** [comment]
Hi, if your country blocks Pornhub, this API is blocked too.
You can use proxies like so:

```py
import phub

client = phub.Client(proxies = {'https': '<protocol>://<ip>'})
```

Hope this helps!

**Comment by bobwatcherx** [comment]
how to make own proxy server . with python and can i deploy self
you have tutorial or package . i will deploy in my vps

**Comment by EchterAlsFake** [comment]
Sorry, but we can't help you with that. Please use an online tutorial for that.

Good Luck.
